version: '3.4'
services:
    sonarqube:
        image: sonarqube
        ports:
            - "9000:9000"
    gitlab:
        image: gitlab/gitlab-ce:latest
        container_name: my_gitlab
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                gitlab_rails['initial_root_password'] = 'adminadmin'
                gitlab_rails['registry_enabled'] = true
                gitlab_rails['registry_host'] = 'my_registry'
                gitlab_rails['registry_port'] = '5000'                
            #gitlab_rails['initial_root_email'] = 'adminadmin@email.com'
            #GITLAB_ROOT_PASSWORD: "admin"
            #GITLAB_ROOT_EMAIL: "hello@world.com"
        ports:
            - "10080:80"
            - "10443:443"
            - "10022:22"
        networks:
            - frontend
    runner:
        build:
            context: .
            dockerfile: runner-dockerfile
#       image: centos:8
#       ports:
#           - "20022:22"
    registry:
        image: registry:2
        container_name: my_registry
        ports:
            - "35000:5000"
        networks:
            - frontend
    jenkins:
        image: jenkins/jenkins:lts
        ports:
            - "58080:8080"
            - "50000:50000" 
        
# bump2
#https://docs.docker.com/compose/networking/
#
# needed to issue the following in order to get inter-container communication functioning on fedora-latest-stable
# kudos: https://stackoverflow.com/questions/40214617/docker-no-route-to-host
#sysctl net.bridge.bridge-nf-call-iptables=0
#sysctl net.bridge.bridge-nf-call-arptables=0
#sysctl net.bridge.bridge-nf-call-ip6tables=0
networks:
  frontend:
    driver: bridge