version: '3.4'
services:
#    sonarqube:
#        image: sonarqube
#        ports:
#            - "9000:9000"
    gitlab:
        image: gitlab/gitlab-ce:latest
        container_name: my_gitlab
        environment:
        #http://localhost:10080/help/administration/packages/container_registry.md
            GITLAB_OMNIBUS_CONFIG: |
                gitlab_rails['initial_root_password'] = 'adminadmin'
                gitlab_rails['registry_enabled'] = true
                gitlab_rails['registry_host'] = 'localhost'
                gitlab_rails['registry_port'] = '35000'
                gitlab_rails['registry_api_url'] = 'http://localhost:35000/'
            #gitlab_rails['initial_root_email'] = 'adminadmin@email.com'
            #GITLAB_ROOT_PASSWORD: "admin"
            #GITLAB_ROOT_EMAIL: "hello@world.com"
        ports:
            - "10080:80"
            - "10443:443"
            - "10022:22"
        networks:
            - bridge
#    runner:
        #https://www.ikus-soft.com/en/blog/2018-05-23-how-to-setup-gitlab-cicd/
#        build:
#            context: .
#            dockerfile: runner-dockerfile
#       image: centos:8
#       ports:
#           - "20022:22"
    registry:
        image: registry:2
        container_name: my_registry
        ports:
            - "35000:5000"
        networks:
            - bridge
    jenkins:
        build:
            context: .
            dockerfile: Dockerfile.jenkins
        environment:
            # from https://stackoverflow.com/questions/44727535/jenkins-docker-set-admin-password-from-environment-variable
            JAVA_OPTS: -Djenkins.install.runSetupWizard=false
            JENKINS_OPTS: --argumentsRealm.roles.user=root --argumentsRealm.passwd.admin=adminadmin --argumentsRealm.roles.admin=admin
        ports:
            - "58080:8080"
            - "50000:50000" 
        networks:
            - bridge

#    snyk:
#        image: snyk/snyk-cli
#https://docs.docker.com/compose/networking/
#
# needed to issue the following in order to get inter-container communication functioning on fedora-latest-stable
# kudos: https://stackoverflow.com/questions/40214617/docker-no-route-to-host
#sysctl net.bridge.bridge-nf-call-iptables=0
#sysctl net.bridge.bridge-nf-call-arptables=0
#sysctl net.bridge.bridge-nf-call-ip6tables=0
#sysctl net.ipv4.ip_forward=1
#also had to turn off firewalld 
networks:
  bridge:
    driver: bridge